version: "3.9"

services:
  postgresql:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=vulntools
    ports:
      - 5432:5432
    # Make postgresql data persistent
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
